#!/usr/bin/python3
"""
Filter MAF oncoKB file

Author:TC Chang
"""

import csv
import sys
import os
import argparse
from collections import defaultdict
from pprint import pformat
import math

version = '1.0.05052022'


def get_args():
	parser = argparse.ArgumentParser(description = __doc__)
	parser.add_argument(
                '-f','--maffile',
                metavar='<maffile>',
                help='File should be .maf file '
                        'generated by oncokb annotator'
        )
	#parser.add_argument(
       # 	'-o', '--outfile',
       # 	metavar='<outfile>',
       # 	help='output the file'
    	#)
	parser.add_argument(
                '-v', '--version',
                action = 'version',
                version = '%(prog)s - v' + version
        )

	args = parser.parse_args()
	
	if (args.maffile is None):
		sys.stderr.write("ERROR: You must input a MOMA .maf file \n")
		sys.exit(1)
	return args

def main(maffile):
	#if outfile:
	#	sys.stderr.write('Writing data to %s\n' % outfile)
	#	outfh = open(outfile, 'w')
	#else:
	#	outfh = sys.stdout
	#csv_writer = csv.writer(outfh)

	with open(maffile, "r") as afile:
		for line in afile:
			if not line.startswith("Hugo_Symbol"):
				line = line.split("\t")
				MUTATION_EFFECT = str(line[42])
				ONCOGENIC = str(line[43])
				HIGHEST_LEVEL = str(line[52])
				CITATIONS = str(line[53])
			
				if "Unknown" not in MUTATION_EFFECT or "Unknown" not in ONCOGENIC:
					line = [i.replace('\n','') for i in line]
					item = "\t".join(line)
					print (item)
					#csv_writer.writerow(line)
				elif HIGHEST_LEVEL != "" or CITATIONS != "":
					line = [i.replace('\n','') for i in line]
					item = "\t".join(line)
					print (item)
					#csv_writer.writerow(line)

			else:
				line = line.split("\t")
				line = [i.replace('\n','') for i in line]
				item = "\t".join(line)
				print (item)
			
if __name__ == '__main__':
	args = get_args()
### Should input countfile and foldchange ###
	main(args.maffile)

